# Generated by Django 2.2.2 on 2019-06-24 12:35

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_fixtures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='location',
            field=models.CharField(default='None', max_length=40),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.CharField(default='Guest', max_length=40),
        ),
        migrations.AlterField(
            model_name='task',
            name='worker_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
